
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Jan 19 16:10:51 CET 2026
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MENOS = 10;
  public static final int IGUALIGUAL = 13;
  public static final int MENOR = 15;
  public static final int ELSE = 3;
  public static final int IGUAL = 12;
  public static final int WHILE = 4;
  public static final int IDEN = 25;
  public static final int TRUE = 7;
  public static final int IF = 2;
  public static final int CC = 20;
  public static final int CA = 19;
  public static final int LC = 22;
  public static final int LA = 21;
  public static final int MAYOR = 14;
  public static final int EOF = 0;
  public static final int TIPO_BOOL = 6;
  public static final int FALSE = 8;
  public static final int error = 1;
  public static final int TIPO_ENT = 5;
  public static final int PC = 18;
  public static final int PUNTOCOMA = 16;
  public static final int PA = 17;
  public static final int PORFAVOR = 23;
  public static final int MUL = 11;
  public static final int ENT = 24;
  public static final int MAS = 9;
}

