
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Jan 19 16:10:51 CET 2026
//----------------------------------------------------

package constructorast;

import java_cup.runtime.*;
import alex.AnalizadorLexicoTiny;
import errors.GestionErroresTiny;
import ast.*;
import java.util.LinkedList;
import java_cup.runtime.ComplexSymbolFactory.Location;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Mon Jan 19 16:10:51 CET 2026
  */
public class ConstructorAST extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ConstructorAST() {super();}

  /** Constructor which sets the default scanner. */
  public ConstructorAST(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ConstructorAST(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\041\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\002\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\004\005\000" +
    "\002\006\005\000\002\006\005\000\002\006\010\000\002" +
    "\006\010\000\002\007\007\000\002\007\012\000\002\007" +
    "\015\000\002\010\007\000\002\010\011\000\002\011\007" +
    "\000\002\012\005\000\002\012\005\000\002\012\005\000" +
    "\002\012\005\000\002\012\005\000\002\012\005\000\002" +
    "\012\005\000\002\012\003\000\002\012\003\000\002\012" +
    "\003\000\002\012\006\000\002\012\003\000\002\013\003" +
    "\000\002\013\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\121\000\016\002\ufffe\004\ufffe\006\ufffe\007\ufffe\010" +
    "\ufffe\031\ufffe\001\002\000\016\002\001\004\015\006\011" +
    "\007\016\010\017\031\013\001\002\000\004\002\006\001" +
    "\002\000\004\002\000\001\002\000\020\002\ufffb\004\ufffb" +
    "\006\ufffb\007\ufffb\010\ufffb\030\ufffb\031\ufffb\001\002\000" +
    "\020\002\ufffc\004\ufffc\006\ufffc\007\ufffc\010\ufffc\030\ufffc" +
    "\031\ufffc\001\002\000\004\023\120\001\002\000\020\002" +
    "\ufffd\004\ufffd\006\ufffd\007\ufffd\010\ufffd\030\ufffd\031\ufffd" +
    "\001\002\000\004\033\076\001\002\000\020\002\ufffa\004" +
    "\ufffa\006\ufffa\007\ufffa\010\ufffa\030\ufffa\031\ufffa\001\002" +
    "\000\004\023\037\001\002\000\004\033\031\001\002\000" +
    "\004\033\021\001\002\000\020\002\uffff\004\uffff\006\uffff" +
    "\007\uffff\010\uffff\030\uffff\031\uffff\001\002\000\006\022" +
    "\023\025\022\001\002\000\004\032\025\001\002\000\020" +
    "\002\ufff7\004\ufff7\006\ufff7\007\ufff7\010\ufff7\030\ufff7\031" +
    "\ufff7\001\002\000\006\026\026\032\027\001\002\000\030" +
    "\005\uffe2\013\uffe2\014\uffe2\015\uffe2\017\uffe2\020\uffe2\021" +
    "\uffe2\022\uffe2\024\uffe2\026\uffe2\032\uffe2\001\002\000\004" +
    "\022\030\001\002\000\030\005\uffe1\013\uffe1\014\uffe1\015" +
    "\uffe1\017\uffe1\020\uffe1\021\uffe1\022\uffe1\024\uffe1\026\uffe1" +
    "\032\uffe1\001\002\000\020\002\ufff5\004\ufff5\006\ufff5\007" +
    "\ufff5\010\ufff5\030\ufff5\031\ufff5\001\002\000\006\022\033" +
    "\025\032\001\002\000\004\032\025\001\002\000\020\002" +
    "\ufff8\004\ufff8\006\ufff8\007\ufff8\010\ufff8\030\ufff8\031\ufff8" +
    "\001\002\000\006\026\035\032\027\001\002\000\004\022" +
    "\036\001\002\000\020\002\ufff6\004\ufff6\006\ufff6\007\ufff6" +
    "\010\ufff6\030\ufff6\031\ufff6\001\002\000\014\011\041\012" +
    "\044\023\043\032\025\033\045\001\002\000\030\005\uffe7" +
    "\013\uffe7\014\uffe7\015\uffe7\017\uffe7\020\uffe7\021\uffe7\022" +
    "\uffe7\024\uffe7\026\uffe7\032\027\001\002\000\026\005\uffe6" +
    "\013\uffe6\014\uffe6\015\uffe6\017\uffe6\020\uffe6\021\uffe6\022" +
    "\uffe6\024\uffe6\026\uffe6\001\002\000\020\013\051\014\054" +
    "\015\053\017\052\020\056\021\055\024\067\001\002\000" +
    "\014\011\041\012\044\023\043\032\025\033\045\001\002" +
    "\000\026\005\uffe5\013\uffe5\014\uffe5\015\uffe5\017\uffe5\020" +
    "\uffe5\021\uffe5\022\uffe5\024\uffe5\026\uffe5\001\002\000\030" +
    "\005\uffe3\013\uffe3\014\uffe3\015\uffe3\017\uffe3\020\uffe3\021" +
    "\uffe3\022\uffe3\024\uffe3\025\046\026\uffe3\001\002\000\014" +
    "\011\041\012\044\023\043\032\025\033\045\001\002\000" +
    "\020\013\051\014\054\015\053\017\052\020\056\021\055" +
    "\026\050\001\002\000\026\005\uffe4\013\uffe4\014\uffe4\015" +
    "\uffe4\017\uffe4\020\uffe4\021\uffe4\022\uffe4\024\uffe4\026\uffe4" +
    "\001\002\000\014\011\041\012\044\023\043\032\025\033" +
    "\045\001\002\000\014\011\041\012\044\023\043\032\025" +
    "\033\045\001\002\000\014\011\041\012\044\023\043\032" +
    "\025\033\045\001\002\000\014\011\041\012\044\023\043" +
    "\032\025\033\045\001\002\000\014\011\041\012\044\023" +
    "\043\032\025\033\045\001\002\000\014\011\041\012\044" +
    "\023\043\032\025\033\045\001\002\000\026\005\uffeb\013" +
    "\051\014\054\015\053\017\uffeb\020\uffeb\021\uffeb\022\uffeb" +
    "\024\uffeb\026\uffeb\001\002\000\026\005\uffea\013\051\014" +
    "\054\015\053\017\uffea\020\uffea\021\uffea\022\uffea\024\uffea" +
    "\026\uffea\001\002\000\026\005\uffed\013\uffed\014\uffed\015" +
    "\053\017\uffed\020\uffed\021\uffed\022\uffed\024\uffed\026\uffed" +
    "\001\002\000\026\005\uffec\013\uffec\014\uffec\015\uffec\017" +
    "\uffec\020\uffec\021\uffec\022\uffec\024\uffec\026\uffec\001\002" +
    "\000\026\005\uffe9\013\051\014\054\015\053\017\uffe9\020" +
    "\056\021\055\022\uffe9\024\uffe9\026\uffe9\001\002\000\026" +
    "\005\uffee\013\uffee\014\uffee\015\053\017\uffee\020\uffee\021" +
    "\uffee\022\uffee\024\uffee\026\uffee\001\002\000\020\013\051" +
    "\014\054\015\053\017\052\020\056\021\055\024\066\001" +
    "\002\000\026\005\uffe8\013\uffe8\014\uffe8\015\uffe8\017\uffe8" +
    "\020\uffe8\021\uffe8\022\uffe8\024\uffe8\026\uffe8\001\002\000" +
    "\004\027\071\001\002\000\022\002\ufff1\004\ufff1\005\074" +
    "\006\ufff1\007\ufff1\010\ufff1\030\ufff1\031\ufff1\001\002\000" +
    "\016\004\ufffe\006\ufffe\007\ufffe\010\ufffe\030\ufffe\031\ufffe" +
    "\001\002\000\016\004\015\006\011\007\016\010\017\030" +
    "\073\031\013\001\002\000\022\002\ufff9\004\ufff9\005\ufff9" +
    "\006\ufff9\007\ufff9\010\ufff9\030\ufff9\031\ufff9\001\002\000" +
    "\004\027\071\001\002\000\020\002\ufff0\004\ufff0\006\ufff0" +
    "\007\ufff0\010\ufff0\030\ufff0\031\ufff0\001\002\000\006\016" +
    "\100\025\077\001\002\000\014\011\041\012\044\023\043" +
    "\032\025\033\045\001\002\000\016\004\102\011\041\012" +
    "\044\023\043\032\025\033\045\001\002\000\020\013\051" +
    "\014\054\015\053\017\052\020\056\021\055\022\112\001" +
    "\002\000\004\023\103\001\002\000\014\011\041\012\044" +
    "\023\043\032\025\033\045\001\002\000\020\013\051\014" +
    "\054\015\053\017\052\020\056\021\055\024\105\001\002" +
    "\000\014\011\041\012\044\023\043\032\025\033\045\001" +
    "\002\000\020\005\107\013\051\014\054\015\053\017\052" +
    "\020\056\021\055\001\002\000\014\011\041\012\044\023" +
    "\043\032\025\033\045\001\002\000\020\013\051\014\054" +
    "\015\053\017\052\020\056\021\055\022\111\001\002\000" +
    "\020\002\ufff2\004\ufff2\006\ufff2\007\ufff2\010\ufff2\030\ufff2" +
    "\031\ufff2\001\002\000\020\002\ufff4\004\ufff4\006\ufff4\007" +
    "\ufff4\010\ufff4\030\ufff4\031\ufff4\001\002\000\020\013\051" +
    "\014\054\015\053\017\052\020\056\021\055\026\114\001" +
    "\002\000\004\016\115\001\002\000\014\011\041\012\044" +
    "\023\043\032\025\033\045\001\002\000\020\013\051\014" +
    "\054\015\053\017\052\020\056\021\055\022\117\001\002" +
    "\000\020\002\ufff3\004\ufff3\006\ufff3\007\ufff3\010\ufff3\030" +
    "\ufff3\031\ufff3\001\002\000\014\011\041\012\044\023\043" +
    "\032\025\033\045\001\002\000\020\013\051\014\054\015" +
    "\053\017\052\020\056\021\055\024\122\001\002\000\004" +
    "\027\071\001\002\000\020\002\uffef\004\uffef\006\uffef\007" +
    "\uffef\010\uffef\030\uffef\031\uffef\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\121\000\006\002\004\003\003\001\001\000\014\005" +
    "\017\006\011\007\007\010\006\011\013\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\013\023\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\033\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\012\041\013\037\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\012\064" +
    "\013\037\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\012\046\013\037\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\012\063\013\037\001\001\000\006\012" +
    "\062\013\037\001\001\000\006\012\061\013\037\001\001" +
    "\000\006\012\060\013\037\001\001\000\006\012\057\013" +
    "\037\001\001\000\006\012\056\013\037\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\067\001\001\000\002\001" +
    "\001\000\004\003\071\001\001\000\014\005\017\006\011" +
    "\007\007\010\006\011\013\001\001\000\002\001\001\000" +
    "\004\004\074\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\012\112\013\037\001\001\000\006\012\100\013" +
    "\037\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\012\103\013\037\001\001\000\002\001\001\000\006\012" +
    "\105\013\037\001\001\000\002\001\001\000\006\012\107" +
    "\013\037\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\012\115\013\037\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\012\120\013\037\001\001\000\002\001\001" +
    "\000\004\004\122\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ConstructorAST$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ConstructorAST$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ConstructorAST$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

  errores = new GestionErroresTiny();
  AnalizadorLexicoTiny alex = (AnalizadorLexicoTiny) getScanner();
  alex.fijaGestionErrores(errores);

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return getScanner().next_token(); 
    }


  private GestionErroresTiny errores;

  public void syntax_error(Symbol token) {
    errores.errorSintactico(token);
  }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ConstructorAST$actions {
  private final ConstructorAST parser;

  /** Constructor */
  CUP$ConstructorAST$actions(ConstructorAST parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ConstructorAST$do_action_part00000000(
    int                        CUP$ConstructorAST$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorAST$parser,
    java.util.Stack            CUP$ConstructorAST$stack,
    int                        CUP$ConstructorAST$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ConstructorAST$result;

      /* select the action based on the action number */
      switch (CUP$ConstructorAST$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Programa ::= ListaInst 
            {
              LinkedList<Instruccion> RESULT =null;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = l; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Programa",0, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Programa EOF 
            {
              Object RESULT =null;
		LinkedList<Instruccion> start_val = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		RESULT = start_val;
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$ConstructorAST$parser.done_parsing();
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // ListaInst ::= ListaInst Inst 
            {
              LinkedList<Instruccion> RESULT =null;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 l.add(i); RESULT = l; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("ListaInst",1, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // ListaInst ::= 
            {
              LinkedList<Instruccion> RESULT =null;
		 RESULT = new LinkedList<Instruccion>(); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("ListaInst",1, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Inst ::= Decl 
            {
              Instruccion RESULT =null;
		Instruccion d = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = d; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Inst ::= Asig 
            {
              Instruccion RESULT =null;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = a; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Inst ::= Cond 
            {
              Instruccion RESULT =null;
		Instruccion c = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = c; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Inst ::= Bucle 
            {
              Instruccion RESULT =null;
		Instruccion b = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = b; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Bloque ::= LA ListaInst LC 
            {
              LinkedList<Instruccion> RESULT =null;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = l; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Bloque",2, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Decl ::= TIPO_ENT IDEN PUNTOCOMA 
            {
              Instruccion RESULT =null;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Declaracion(Type.NUM, (String)id); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Decl",4, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Decl ::= TIPO_BOOL IDEN PUNTOCOMA 
            {
              Instruccion RESULT =null;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Declaracion(Type.BOOL, (String)id); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Decl",4, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Decl ::= TIPO_ENT IDEN CA Numero CC PUNTOCOMA 
            {
              Instruccion RESULT =null;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-4)).value;
		String n = (String)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		 RESULT = new DeclaracionArray(Type.NUM, (String)id, Integer.parseInt(n)); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Decl",4, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Decl ::= TIPO_BOOL IDEN CA Numero CC PUNTOCOMA 
            {
              Instruccion RESULT =null;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-4)).value;
		String n = (String)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		 RESULT = new DeclaracionArray(Type.BOOL, (String)id, Integer.parseInt(n)); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Decl",4, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Asig ::= PORFAVOR IDEN IGUAL Exp PUNTOCOMA 
            {
              Instruccion RESULT =null;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Asignacion((String)id, e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Asig",5, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Asig ::= PORFAVOR IDEN CA Exp CC IGUAL Exp PUNTOCOMA 
            {
              Instruccion RESULT =null;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-6)).value;
		E i = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-4)).value;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new AsignacionArray((String)id, i, e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Asig",5, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Asig ::= PORFAVOR IDEN IGUAL IF PA Exp PC Exp ELSE Exp PUNTOCOMA 
            {
              Instruccion RESULT =null;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-9)).value;
		E c = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-5)).value;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new AsignacionCondicional((String)id, c, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Asig",5, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Cond ::= IF PA Exp PC Bloque 
            {
              Instruccion RESULT =null;
		E c = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		LinkedList<Instruccion> b = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Condicional(c, b, null); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Cond",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Cond ::= IF PA Exp PC Bloque ELSE Bloque 
            {
              Instruccion RESULT =null;
		E c = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-4)).value;
		LinkedList<Instruccion> b1 = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		LinkedList<Instruccion> b2 = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Condicional(c, b1, b2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Cond",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Bucle ::= WHILE PA Exp PC Bloque 
            {
              Instruccion RESULT =null;
		E c = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		LinkedList<Instruccion> b = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Bucle(c, b); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Bucle",7, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Exp ::= Exp MAS Exp 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.MAS, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Exp ::= Exp MENOS Exp 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.RESTA, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Exp ::= Exp MUL Exp 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.MULT, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Exp ::= Exp MAYOR Exp 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.MAYOR, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Exp ::= Exp MENOR Exp 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.MENOR, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Exp ::= Exp IGUALIGUAL Exp 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.IGUAL, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Exp ::= PA Exp PC 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Exp ::= Numero 
            {
              E RESULT =null;
		String n = (String)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Num(n); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // Exp ::= TRUE 
            {
              E RESULT =null;
		 RESULT = new BoolValue("true"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Exp ::= FALSE 
            {
              E RESULT =null;
		 RESULT = new BoolValue("false"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Exp ::= IDEN CA Exp CC 
            {
              E RESULT =null;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		E i = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new AccesoArray((String)id, i); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Exp ::= IDEN 
            {
              E RESULT =null;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Identificador((String)id); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Exp",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // Numero ::= ENT 
            {
              String RESULT =null;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = (String)n; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Numero",9, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Numero ::= Numero ENT 
            {
              String RESULT =null;
		String ns = (String)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = ns + (String)n; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Numero",9, RESULT);
            }
          return CUP$ConstructorAST$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ConstructorAST$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ConstructorAST$do_action(
    int                        CUP$ConstructorAST$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorAST$parser,
    java.util.Stack            CUP$ConstructorAST$stack,
    int                        CUP$ConstructorAST$top)
    throws java.lang.Exception
    {
              return CUP$ConstructorAST$do_action_part00000000(
                               CUP$ConstructorAST$act_num,
                               CUP$ConstructorAST$parser,
                               CUP$ConstructorAST$stack,
                               CUP$ConstructorAST$top);
    }
}

